## 무작정 따라하기

### 0. 환경준비

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plot
from sklearn.model_selection import train_test_split

import warnings
warnings.filterwarnings(action='ignore')

### 1. 데이터 로딩

In [2]:
path = 'https://raw.githubusercontent.com/DA4BAM/dataset/master/advertising.csv'
data = pd.read_csv(path)

data.head()

      TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

- TV, Radio, Newspaper 광고비용 지출에 따른 판매액 데이터
- 광고비용에 따른 매출액

### 2. 데이터 전처리

#### 1) 데이터를 X와 y로 나누기
- X: features, input
- y: target, output

In [4]:
target = 'Sales'
x = data.drop(target, axis=1)
y = data.loc[:, target]

In [5]:
x.head()

      TV  Radio  Newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
2   17.2   45.9       69.3
3  151.5   41.3       58.5
4  180.8   10.8       58.4

In [6]:
y.head()

0    22.1
1    10.4
2     9.3
3    18.5
4    12.9
Name: Sales, dtype: float64

#### 2) train, validation, test로 분할

In [7]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3)

### 3. 학습

In [8]:
# 필요한 함수들 불러오기
from sklearn.linear_model import LinearRegression

from sklearn.metrics import mean_absolute_error

In [10]:
# 모델 선언하기
model = LinearRegression()

In [11]:
# 학습
model.fit(x_train, y_train)

LinearRegression()

### 4. 예측
- 학습의 결과 모델이 만들어짐
- 모델이 얼마나 정확한지 검증

In [12]:
pred = model.predict(x_test)
pred

array([15.44879715, 10.02542   , 15.81174589, 14.29820885, 18.04544697,
       13.94593875, 15.63052079, 18.75349151,  7.42467152, 18.70458921,
       14.84095237, 14.78543254, 21.54538344, 23.98200536, 14.45955819,
       20.77452798, 12.17205705, 12.1393189 , 10.77321342, 20.33508828,
       16.83598802, 18.8893828 , 21.49029889,  6.7596528 ,  9.1176337 ,
       10.96498503, 20.49059141,  8.25218033, 13.65576416, 15.13450912,
       14.11287885, 16.45458332,  9.41356636, 23.14032921, 10.29537487,
       16.32413042,  9.86484337, 21.25680935,  8.17252095, 13.52387874,
       17.02125307, 15.65891675, 11.85054107,  6.23706005, 11.78997312,
       16.16696818, 11.95261699, 16.74732259, 12.38862469, 15.98542915,
       12.75998492, 10.79018765,  6.68545363, 13.84092333, 10.46838894,
       15.14092368,  8.86779611, 18.11543149, 10.63336588, 17.01836989])

### 5. 평가

In [13]:
# 평균 오차
mean_absolute_error(y_test, pred)

1.369667865284483

## 실습1 : Diamond Price 예측

### 1. 데이터 로딩

In [14]:
path = 'https://raw.githubusercontent.com/DA4BAM/dataset/master/diamonds.csv'
data = pd.read_csv(path)
data = data.sample(2000, random_state=_state=2022)
data.head()

       carat        cut color clarity  depth  table  price     x     y     z
50989   0.31      Ideal     G     VS2   61.6   55.0    544  4.37  4.39  2.70
42221   0.33      Ideal     E      IF   62.1   55.0   1289  4.43  4.46  2.76
42307   0.41      Ideal     F    VVS1   62.1   57.0   1295  4.75  4.79  2.96
27207   2.02  Very Good     F     SI1   62.7   59.0  17530  7.97  8.03  5.02
22207   1.50       Good     H     VS1   63.4   59.0  10256  7.20  7.29  4.59

### 2. 데이터 전처리

In [15]:
# x, y 분할
target = 'price'
x = data.drop(target, axis=1)
y = data.loc[:, target]

In [16]:
# 가변수화
col_cat = ['cut', 'color', 'clarity']
x = pd.get_dummies(x, columns=col_cat, drop_first=True)

In [17]:
# train, test 분할
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3)

### 3. 학습

In [18]:
from sklearn.linear_model import LinearRegression

from sklearn.metrics import mean_absolute_error

In [19]:
model = LinearRegression()

In [20]:
model.fit(x_train, y_train)

LinearRegression()

### 4. 예측

In [21]:
pred = model.predict(x_test)
pred

array([ 3.72967079e+03,  6.41279604e+03,  1.35494212e+03,  3.46259836e+03,
        6.68769277e+03,  1.04238240e+03,  1.05009576e+03,  8.54623937e+03,
        5.97082582e+03,  1.64441481e+03,  4.42366756e+03, -3.11998244e+02,
       -8.56557590e+02,  7.54660131e+03,  7.64931006e+02,  5.95276484e+03,
       -4.65782017e+02,  6.37202733e+03, -3.69718792e+01,  1.95626314e+03,
        4.56043835e+03,  7.51740332e+03,  5.30592767e+03,  1.53352719e+03,
        2.31487978e+03,  4.88436505e+03,  1.50865610e+03,  2.06695751e+03,
        1.16853226e+04,  1.56455081e+03,  3.23497525e+03,  2.83089315e+02,
        2.31973209e+03,  4.43123405e+03,  1.96686332e+03,  2.26685453e+03,
       -2.73652949e+02,  1.16290628e+04,  3.62951782e+03,  1.07400724e+04,
        4.20405454e+03,  9.12067364e+03,  3.49074343e+03,  8.04363898e+01,
        4.25515101e+02,  6.39840353e+03, -5.43462789e+02,  4.42052023e+03,
        4.44456737e+03,  1.12896693e+03,  6.86512658e+03,  8.31993210e+03,
        9.19932941e+02,  1.36555449e+03,  6.00295778e+01,  5.08638673e+02,
        2.80000769e+03,  2.39297166e+02,  2.54366637e+03,  3.38177879e+03,
        1.48036267e+03,  1.02446883e+03,  1.85092041e+02,  1.19278163e+04,
        7.11651305e+03,  6.37298492e+03,  2.90852808e+03, -3.50087783e+02,
       -8.17918015e+02,  5.14636899e+02,  1.73241580e+04,  1.14693946e+04,
        5.98118656e+02,  6.45527180e+03,  1.50086319e+02, -7.68948776e+02,
        7.88125202e+03,  2.46433453e+03,  9.27149150e+03,  1.15525779e+03,
        8.41610465e+03, -1.41781976e+02,  6.24011304e+02,  7.90473562e+03,
        2.96739690e+03,  6.12191415e+03,  2.79097194e+03,  6.39790296e+03,
        2.45140046e+03,  1.16153373e+03,  3.27226213e+03,  3.68355590e+03,
        2.75293946e+03,  4.15363096e+03,  1.14873707e+04,  1.80174557e+03,
        1.84852819e+03,  6.27716540e+03,  2.99841104e+03,  8.12443342e+03,
        1.00005777e+03,  4.80474887e+02,  3.55274503e+03,  1.03618004e+03,
        7.27002020e+02,  4.73882424e+03,  3.03120228e+03,  4.44465281e+03,
        5.45284564e+03,  5.76000198e+03,  5.04477619e+03,  1.38304564e+04,
        6.79411999e+02,  6.25102927e+02,  3.74267926e+01,  1.48680630e+04,
        2.34264077e+03,  3.44598957e+02,  2.45363083e+03,  2.70252859e+03,
        1.49075355e+04,  5.13148821e+03, -6.61511748e+01,  7.19465481e+03,
        1.25806194e+04,  7.57238607e+03,  3.96621858e+03, -1.82470360e+03,
        2.16625491e+03,  6.36248331e+03,  1.57975299e+03,  5.62479534e+03,
        3.13505182e+03,  1.61394492e+03,  7.82176676e+03,  7.88780589e+02,
        1.92065092e+03,  5.62849155e+03,  2.41493127e+03, -1.28080253e+03,
        4.29570152e+03,  1.27344617e+04,  1.21221257e+03,  3.26120736e+03,
        7.38008968e+02,  1.42019202e+03,  6.17155088e+03,  6.49991347e+03,
        1.86800501e+03,  1.05432295e+04,  2.37814248e+02,  6.10870173e+03,
        1.08675632e+03,  8.48352191e+03,  1.99456150e+03,  1.01492280e+04,
        2.13963413e+03, -1.67276543e+03,  3.89511893e+03,  8.33924836e+02,
        4.07948793e+03,  1.96339802e+03,  1.17649870e+03,  1.28404354e+04,
        8.24301982e+03,  5.28293149e+03,  6.02306562e+03,  6.44414604e+03,
        5.84019712e+03,  4.38821324e+03,  8.21889863e+03,  1.29439558e+04,
        1.25019118e+03,  1.91807018e+03,  1.26210748e+03,  2.44369808e+03,
        6.22364534e+02, -8.24927568e+02,  9.31543289e+03,  1.42341354e+04,
        7.89605451e+03,  3.78881378e+03,  4.75024835e+03,  3.76229225e+03,
        1.52444498e+03,  1.34648309e+02,  5.54372488e+03,  3.11312653e+04,
        4.39310749e+03,  4.81702976e+03,  1.07003852e+03,  4.39427901e+03,
        5.27089744e+03,  5.37522780e+02,  6.07557016e+03,  7.55418128e+03,
        7.72017739e+03, -1.97530478e+03,  9.93826197e+03,  1.09882953e+03,
        1.97222617e+03,  3.30911074e+03,  7.47019435e+02,  5.82931121e+02,
        3.15034560e+03,  9.04687756e+02, -1.24129768e+03, -2.04724782e+03,
        5.69561580e+03,  3.99834543e+03,  1.23761377e+04,  1.41018067e+04,
        2.26271112e+03,  1.21082754e+03,  6.22954727e+03,  6.86763272e+03,
        1.18829917e+03,  6.09609017e+03,  1.24916051e+03,  4.66029473e+03,
       -3.54078893e+03,  2.03809262e+03,  6.36187692e+03,  5.48074817e+03,
        2.36073476e+03,  2.13699085e+03,  3.05981085e+03,  2.78258072e+03,
        6.49090534e+03,  1.02005064e+02,  1.79918948e+03,  1.47557218e+03,
        1.80064265e+03,  1.29788731e+03,  1.76956127e+01,  2.18631638e+03,
        1.41662195e+03,  4.74419652e+03,  3.74357364e+03,  1.01528184e+04,
        5.61973335e+03,  3.49022244e+03,  1.36560568e+03,  5.97919646e+03,
        2.82497696e+03,  1.02632808e+04,  9.50408468e+03,  4.63377976e+03,
        8.35773807e+03,  4.37822886e+02,  1.10324376e+04,  8.30091251e+02,
        2.30032290e+03, -1.04521499e+03,  3.84458662e+02,  1.63304841e+03,
        2.56252403e+03,  6.61770739e+03,  1.33342976e+02,  3.50434275e+03,
       -1.87752710e+02, -1.44445504e+02, -2.21132089e+03,  3.22296953e+03,
        2.14411409e+03,  2.57188643e+03,  2.78997255e+02,  2.10639031e+03,
        1.21871629e+04,  1.93981228e+03,  7.48005494e+03,  2.36509200e+03,
        1.17761558e+04,  5.45644266e+03,  1.88746518e+03,  4.26504515e+03,
        4.46283585e+02,  1.07584846e+03,  2.66974969e+03,  6.64471135e+02,
        4.88309227e+03,  3.87690838e+03,  5.16040201e+02,  2.16930079e+03,
        5.23195577e+02,  4.45812864e+03,  1.10361464e+03,  1.22309068e+03,
        1.06124007e+04,  7.04239070e+02,  4.38820521e+03,  4.84044809e+02,
        1.33481935e+03,  3.56131570e+03,  2.70525187e+03,  1.39365794e+03,
        9.74885176e+03,  4.85434234e+03,  3.22843919e+03,  4.71377710e+03,
        7.41047542e+02,  8.72309722e+03,  1.17987482e+03,  4.19928292e+01,
        2.78053721e+03,  3.64616171e+03,  4.63426063e+03,  9.24007680e+01,
       -3.58891925e+02,  1.08942712e+03,  7.93386018e+03,  6.10596620e+02,
        1.46626032e+04, -7.14564459e+02,  2.47490938e+02,  1.52769884e+04,
        2.95716228e+02, -2.38046403e+02,  3.85344015e+03,  4.61457820e+03,
        5.97401191e+03,  1.06657242e+04,  4.85267917e+03,  5.16362475e+03,
        1.86142915e+03,  1.60193221e+03,  1.21356145e+04,  7.50987282e+02,
        8.68664965e+02,  5.14981283e+03,  8.88264733e+02,  1.38701705e+04,
       -1.31163957e+02, -4.48290900e+02,  1.32449894e+03,  3.56550531e+03,
        5.08488112e+03,  6.02432657e+02,  6.64984743e+02,  2.60516052e+03,
        3.89251208e+02,  3.05192929e+03,  2.16532945e+03,  1.51393375e+03,
        2.28957768e+03,  3.79259884e+03,  4.87384357e+03,  1.27691456e+04,
        6.46596603e+03,  3.70414227e+03,  1.81205269e+03, -1.63575267e+02,
        5.85802905e+03,  2.50748882e+03,  6.15282708e+03,  2.36821203e+03,
        9.60653638e+03,  1.39502759e+03,  6.39084751e+03,  9.78523657e+02,
        1.82360599e+03,  1.08529769e+03,  1.93576900e+03,  8.31800489e+03,
        7.72265474e+02,  1.51780899e+03,  2.38889450e+03,  9.46573411e+02,
        1.84240331e+03, -2.31702946e+02,  5.42234649e+02,  1.09998836e+04,
        2.80531971e+03,  8.83126708e+02,  2.98388909e+03,  2.47275939e+03,
        1.44915639e+04,  1.39109622e+03,  8.16454938e+03, -3.88128701e+02,
        1.10108302e+04,  5.52360020e+03,  1.03796583e+03,  4.95273146e+02,
        1.31556590e+03,  6.87119850e+03, -1.04375385e+03,  2.88954402e+02,
       -3.24706881e+03,  3.42038984e+03,  1.39654030e+03,  1.41190858e+01,
        1.01755571e+04,  6.48989504e+03,  2.96678711e+03,  4.57386994e+03,
        1.89895849e+02,  1.05679294e+03,  1.03739930e+04,  4.39351542e+01,
        2.11588869e+03,  1.01386435e+03,  1.16436632e+03,  5.31185124e+03,
        6.26139983e+03,  4.60029358e+03,  4.78126509e+03,  2.81471818e+03,
        1.96212573e+03,  3.96782264e+03,  5.77326501e+02,  3.82205935e+03,
        6.16658657e+03,  1.38884123e+03,  5.55869422e+03,  8.59519648e+03,
        2.42822111e+03,  1.15239534e+03,  2.47897718e+02,  4.74082239e+03,
        1.42644281e+03,  4.26101679e+03,  7.35626440e+02,  1.33536785e+04,
        2.16921711e+03,  6.18833162e+02,  5.01809620e+03,  2.06004888e+03,
        1.25146536e+03,  3.32319172e+03,  1.47050463e+03,  1.74852037e+03,
        9.90518153e+03,  4.02746046e+03,  1.29568176e+03,  1.41888908e+03,
        4.10340548e+03,  1.14517673e+03,  5.93284951e+03,  7.75327912e+03,
        1.78872075e+03,  6.09389280e+03,  1.10305141e+03,  2.55206988e+03,
        1.69002396e+03,  7.67931481e+03,  1.97063340e+03,  2.07142255e+03,
        1.83449175e+03,  9.01933984e+03, -2.34494813e+01,  7.42751593e+03,
        5.48881734e+03,  9.12491296e+03,  1.78706879e+02,  7.29729085e+03,
        5.35753638e+02,  4.76772356e+02,  1.01197773e+04,  7.75528454e+02,
        1.05342682e+03,  2.36468465e+03,  1.64377225e+03,  3.41082820e+03,
        4.57318832e+03,  8.29374320e+03,  6.47934019e+03,  3.15561396e+03,
        1.36671338e+03,  6.75360118e+03,  3.53040512e+03,  1.41085531e+04,
        5.91576759e+03,  5.84055648e+03,  2.71312610e+03,  9.03379034e+02,
        1.42298772e+03,  1.91135556e+04,  9.94004554e+03,  9.10682247e+02,
        3.07209150e+03,  6.70016873e+03,  8.49420449e+03,  1.39970581e+02,
        1.16106973e+04,  2.95957178e+02,  1.09736244e+04,  1.09192629e+04,
        6.69731506e+02,  1.09703488e+04,  4.84454223e+02,  1.27797827e+03,
        4.88454038e+03,  7.54849163e+02,  1.36105975e+04,  4.18184957e+03,
        5.32772277e+02,  1.99503647e+03,  4.96490347e+03,  5.51521657e+03,
        1.12981092e+03,  4.94508096e+02,  2.89475572e+03,  1.88031877e+03,
        5.05614711e+03, -4.01202221e+02,  6.55973622e+03,  2.02205382e+03,
        7.16512123e+03,  1.39316388e+04,  1.17051553e+03,  4.40427806e+03,
        7.41119612e+02,  2.01427991e+03,  2.86591298e+03,  5.31968109e+03,
        1.25156082e+03,  4.22224566e+03,  1.12178561e+03,  5.90405433e+03,
        3.10410335e+03,  9.87915413e+02,  1.07857106e+03,  1.84886141e+03,
        1.77608065e+03,  5.80327839e+03,  1.15519982e+04,  3.65194058e+03,
        1.25772100e+03,  2.74205846e+03,  2.44020176e+03,  7.00015331e+03,
        7.85719294e+03,  2.09393776e+03,  2.28575648e+03,  1.15329196e+04,
        5.66338672e+03,  5.62588310e+02,  1.11513194e+03,  3.86710236e+02,
        5.97494827e+03,  1.86497552e+03,  7.25332161e+02,  2.45984717e+03,
        3.40883674e+03,  4.74702325e+02, -1.28223895e+03,  2.03870431e+03,
        1.48887961e+03,  2.19022323e+03,  9.19498185e+03,  6.22208125e+03,
        4.73191255e+03,  2.56245227e+02, -6.01738127e+02,  1.84356788e+03,
        9.30799363e+03,  8.54414429e+02,  4.74543934e+03,  9.16062197e+03,
        9.55775975e+03,  5.72755999e+03,  2.34015320e+02, -7.91439131e+02,
        1.28878303e+03,  3.91278362e+03,  7.81058876e+02,  6.18594742e+03,
        1.10267440e+04,  1.48731666e+04,  6.13912150e+03,  4.54154152e+03,
        4.04323316e+03,  6.68760016e+03,  2.86369074e+03,  1.65978012e+03,
        2.86229858e+03,  3.37803397e+02,  8.24146214e+02,  7.03318355e+02,
        2.94203303e+03,  2.17716527e+03,  6.00354068e+03,  1.35344747e+04,
       -8.83724771e+02,  6.34550199e+03,  7.99726443e+02,  1.37311277e+04,
        7.24858689e+03,  3.54985092e+03,  7.22388330e+03, -6.95963828e+02,
        2.58071892e+03,  1.09099539e+04, -3.27869108e+02,  1.41259872e+03,
        3.30902294e+01,  7.11637286e+03, -2.83410804e+02,  2.76488501e+03])

### 5. 평가

In [22]:
mean_absolute_error(y_test, pred)

811.405480731183

## 실습2 : 보스턴시 타운별 집값 예측

### 1. 데이터 로딩

In [23]:
path = 'https://raw.githubusercontent.com/DA4BAM/dataset/master/boston.csv'
cols = ['crim','indus','chas','nox','rm', 'dis', 'tax','ptratio','lstat','medv']
data = pd.read_csv(path, usecols=cols)
data.head()

      crim  indus  chas    nox     rm     dis  tax  ptratio  lstat  medv
0  0.00632   2.31     0  0.538  6.575  4.0900  296     15.3   4.98  24.0
1  0.02731   7.07     0  0.469  6.421  4.9671  242     17.8   9.14  21.6
2  0.02729   7.07     0  0.469  7.185  4.9671  242     17.8   4.03  34.7
3  0.03237   2.18     0  0.458  6.998  6.0622  222     18.7   2.94  33.4
4  0.06905   2.18     0  0.458  7.147  6.0622  222     18.7   5.33  36.2

### 2. 데이터 전처리

In [24]:
# x, y 분할
target = 'medv'
x = data.drop(target, axis=1)
y = data.loc[:, target]

In [25]:
# train, test 분할
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3)

### 3. 학습

In [26]:
from sklearn.linear_model import LinearRegression

from sklearn.metrics import mean_absolute_error

In [27]:
model = LinearRegression()

In [28]:
model.fit(x_train, y_train)

LinearRegression()

### 4. 예측

In [29]:
pred = model.predict(x_test)
pred

array([17.18796983, 33.45980829, 35.83365832, 17.50029552, 26.23912148,
       25.64554788, 23.25756849, 11.37221652, 41.50517204, 10.98403998,
       27.07216817, 16.2308305 , 20.54209501, 27.36466212, 32.90729002,
       18.06338953, 28.44214459, 28.15696751, 18.86156809, 30.63890432,
       29.01409258, 21.82377987, 18.33743763, 18.70745346, 32.08538584,
        1.87835   , 23.34506285, 18.80237664, 19.08189159, 21.60670611,
       15.31030547,  0.49670909, 24.3356073 , 17.64863757, 11.21912602,
       13.84033876, 10.83040512, 12.86070036, 17.23276794, 17.76195641,
       25.2579805 , 15.22531726, 42.05895289, 17.98870007, 21.18101057,
       27.04375937, 21.79564113, 20.1942654 , 27.59521949, 24.31567264,
        4.11672544, 24.45703453, 32.69521807, 11.62300328, 16.71684158,
       17.39254544, 17.99685456, 21.05394619, 14.75249743, 10.54460911,
       24.85089526, 23.11655803, 19.82755755, 19.06278451, 18.31190937,
       35.73846546, 25.46812616, 27.90544355, 31.8392701 , 10.30057406,
       25.04525616, 29.55353085, 11.0422208 , 14.69291113, 17.95259687,
       14.82403543, 16.46084589, 27.35564104, 18.58142999, 25.83817156,
        8.4566247 , 10.8358552 , 34.20755046, 16.44549464, 19.47887063,
       24.20822975, 22.18659496,  8.91601324, 23.05521187, 14.70475424,
       22.78202134, 31.69010498, 16.6867215 , 27.56323193,  1.4589796 ,
       17.31232039, 22.67863716, 21.57370497, 22.76123314, 21.41399782,
       21.41802824, 33.79918507, 34.09394776, 26.10694319, 18.14357029,
       38.939763  , 28.00125691, 31.78052698, 22.25197957, 22.10282772,
       34.33215573, 33.05518629,  8.76224457, -4.44895901, 20.66593406,
       10.1137345 , 26.92988359, 18.22169362, 21.68954488, 20.31946701,
       29.84092802,  9.90656231, 22.03267673, 28.37512179, 31.88173689,
        9.28614219,  6.4229502 , 28.8491775 , 13.46243284, 22.73480822,
       20.89362874, 15.7338666 , 23.39585403, 26.44935723, 20.20212851,
       21.1420135 , 38.74453778, 27.78552597, 39.82399256, 23.81188413,
       22.24470056, 18.80697716, 28.46675353, 26.27925555, 36.55213607,
       19.87793343, 14.0005288 , 15.76613424, 16.7363674 , 27.42973687,
       24.23014674,  8.21889386])

### 5. 평가

In [30]:
mean_absolute_error(y_test, pred)

3.758699697602604